import type { Meta, StoryObj } from "@storybook/react-vite";
import { ContractStory } from "./preview-registry";
import { componentStory } from "./story-factory";

const meta = { includeStories: ["Field","SearchField","TextArea","PasswordField","OtpField","Checkbox","Radio","CheckboxGroup","RadioGroup","Switch","Chip","SegmentedControl","Slider","NumberField","Select","Combobox","DatePicker","ColorPicker","FilePicker","Form","Agreement","ToggleGroup","TagsInput","DateRangePicker","Mentions","TransferList"], id: "components-inputs", title: "배포/컴포넌트/입력", component: ContractStory, parameters: { controls: { disable: true } } } satisfies Meta<typeof ContractStory>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Field: Story = { ...componentStory("Field"), name: "입력 필드" };
export const SearchField: Story = { ...componentStory("SearchField"), name: "검색 입력" };
export const TextArea: Story = { ...componentStory("TextArea"), name: "여러 줄 입력" };
export const PasswordField: Story = { ...componentStory("PasswordField"), name: "비밀번호 입력" };
export const OtpField: Story = { ...componentStory("OtpField"), name: "인증번호 입력" };
export const Checkbox: Story = { ...componentStory("Checkbox"), name: "체크박스" };
export const Radio: Story = { ...componentStory("Radio"), name: "라디오 버튼" };
export const CheckboxGroup: Story = { ...componentStory("CheckboxGroup"), name: "체크박스 그룹" };
export const RadioGroup: Story = { ...componentStory("RadioGroup"), name: "라디오 버튼 그룹" };
export const Switch: Story = { ...componentStory("Switch"), name: "스위치" };
export const Chip: Story = { ...componentStory("Chip"), name: "선택 칩" };
export const SegmentedControl: Story = { ...componentStory("SegmentedControl"), name: "버튼형 선택" };
export const Slider: Story = { ...componentStory("Slider"), name: "슬라이더" };
export const NumberField: Story = { ...componentStory("NumberField"), name: "숫자 입력" };
export const Select: Story = { ...componentStory("Select"), name: "목록에서 선택" };
export const Combobox: Story = { ...componentStory("Combobox"), name: "검색형 선택" };
export const DatePicker: Story = { ...componentStory("DatePicker"), name: "날짜 선택" };
export const ColorPicker: Story = { ...componentStory("ColorPicker"), name: "색상 선택기" };
export const FilePicker: Story = { ...componentStory("FilePicker"), name: "파일 선택" };
export const Form: Story = { ...componentStory("Form"), name: "입력 양식" };
export const Agreement: Story = { ...componentStory("Agreement"), name: "약관 동의" };
export const ToggleGroup: Story = { ...componentStory("ToggleGroup"), name: "토글 그룹" };
export const TagsInput: Story = { ...componentStory("TagsInput"), name: "태그 입력" };
export const DateRangePicker: Story = { ...componentStory("DateRangePicker"), name: "기간 선택" };
export const Mentions: Story = { ...componentStory("Mentions"), name: "사용자 언급" };
export const TransferList: Story = { ...componentStory("TransferList"), name: "목록 간 항목 이동" };
