import type { Meta, StoryObj } from "@storybook/react-vite";
import { NotificationItemPreview } from "./common-screen-previews";
const meta = { id: "common-screen-notification-item", title: "실험/구성/공통 화면/알림 항목", component: NotificationItemPreview } satisfies Meta<typeof NotificationItemPreview>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = { name: "기본" };
export const Dark: Story = { name: "어두운 테마", globals: { theme: "dark" } };
export const LargeText: Story = { name: "큰 글자", globals: { textScale: "2" } };
export const Loading: Story = { name: "불러오는 중", args: { stateKind: "loading" } };
export const Empty: Story = { name: "새 소식 없음", args: { stateKind: "empty" } };
export const Error: Story = { name: "연결 복구", args: { stateKind: "error" } };
export const Restricted: Story = { name: "로그인 필요", args: { stateKind: "restricted" } };
export const Recovery: Story = { name: "실패와 초안 복구", args: { tools: true } };
