import type { Meta, StoryObj } from "@storybook/react-vite";
import { Duration, Confirm, Reactions, Notifications } from "./compound-previews";
const meta={ includeStories: ["Default","InlineConfirmation","EmojiReactions","NotificationFeedback","Dark","LargeText"],id: "gallery-compound-controls", title: "배포/구성/비교와 검증/복합 입력 모음",component:Duration} satisfies Meta<typeof Duration>;
export default meta;
export const Default:StoryObj<typeof meta>={ name: "기본",};
export const InlineConfirmation:StoryObj<typeof meta>={ name: "버튼 안에서 확인",render:()=> <Confirm/>};
export const EmojiReactions:StoryObj<typeof meta>={ name: "이모지 반응",render:()=> <Reactions/>};
export const NotificationFeedback:StoryObj<typeof meta>={ name: "알림 상태",render:()=> <Notifications/>};
export const Dark: StoryObj<typeof meta> = { name: "어두운 테마", globals: { theme: "dark" } };
export const LargeText: StoryObj<typeof meta> = { name: "큰 글자", globals: { textScale: "2" } };
