import type { Meta, StoryObj } from "@storybook/react-vite";
import { DesignProfileComparison, DesignProfileFloatingActionComparison } from "./design-profile-preview";
const meta = { id: "design-profile-comparison", includeStories: ["Default", "ProductNotes", "ProductReading", "FloatingAction", "Dark", "LargeText"], title: "실험/구성/비교와 검증/테마 조합", component: DesignProfileComparison } satisfies Meta<typeof DesignProfileComparison>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = { name: "기본" };
export const ProductNotes: Story = { name: "앱 테마 · 산책", args: { initialProduct: "field-notes" } };
export const ProductReading: Story = { name: "앱 테마 · 문장", args: { initialProduct: "reading-room" } };
export const FloatingAction: Story = { name: "플로팅 행동", render: () => <DesignProfileFloatingActionComparison /> };
export const Dark: Story = { name: "어두운 테마", globals: { theme: "dark" } };
export const LargeText: Story = { name: "큰 글자", globals: { textScale: "2" } };
