import type { Meta, StoryObj } from "@storybook/react-vite";
import { ComposerPreview } from "./conversation-previews";
const meta = { id: "purpose-input-comment", title: "배포/구성/입력과 작성/댓글 작성", component: ComposerPreview, args: {purpose:"comment"} } satisfies Meta<typeof ComposerPreview>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {name:"기본"};
export const Pending: Story = {name:"처리 중",args:{initialState:"pending"}};
export const Failed: Story = {name:"실패 후 입력 유지",args:{initialState:"error"}};
export const Dark: Story = {name:"어두운 테마",globals:{theme:"dark"}};
export const LargeText: Story = {name:"큰 글자",globals:{textScale:"2"}};
export const BrandViolet: Story = {name:"제품 색 · 보라",args:{brand:"violet"}};
export const BrandGreenDark: Story = {name:"제품 색 · 초록 · 어두운 테마",args:{brand:"green"},globals:{theme:"dark"}};
