import type { Meta, StoryObj } from "@storybook/react-vite";
import { Effects, Icons, Faces, Transitions } from "./visual-previews";
const meta = { includeStories: ["Default","SemanticLucide","BlobatarFaces","ContentMotion","Dark","LargeText"], id: "gallery-visual-foundations", title: "배포/구성/비교와 검증/시각 효과 모음", component: Effects } satisfies Meta<typeof Effects>;
export default meta;
export const Default: StoryObj<typeof meta> = { name: "기본",};
export const SemanticLucide: StoryObj<typeof meta> = { name: "의미별 루시드 아이콘", render: () => <Icons /> };
export const BlobatarFaces: StoryObj<typeof meta> = { name: "블로바타 표정", render: () => <Faces /> };
export const ContentMotion: StoryObj<typeof meta> = { name: "내용 전환 효과", render: () => <Transitions /> };
export const Dark: StoryObj<typeof meta> = { name: "어두운 테마", globals: { theme: "dark" } };
export const LargeText: StoryObj<typeof meta> = { name: "큰 글자", globals: { textScale: "2" } };
