// Keep API identifiers searchable while presenting purpose-based Korean labels.
// CSF files also declare literal names because the static indexer does not execute helpers.
export const storyLabels: Readonly<Record<string, string>> = {
  "Accordion": "아코디언",
  "Actions": "동작",
  "Affix": "고정 배치",
  "Agreement": "약관 동의",
  "AgreementStory": "약관 동의",
  "AlertDialog": "확인 대화상자",
  "AllStates": "전체 상태",
  "AllStatesDark": "전체 상태 · 어두운 테마",
  "Anchor": "문서 내 바로가기",
  "AspectRatio": "화면 비율",
  "Asset": "이미지·영상 표시",
  "AuthProviderButton": "소셜 로그인 버튼",
  "AuthScreen": "로그인 화면",
  "AuthScreenLayout": "로그인 화면",
  "Avatar": "아바타",
  "BackgroundEffects": "배경 효과",
  "Badge": "배지",
  "BlobatarFaces": "블로바타 표정",
  "BottomCTA": "하단 실행 버튼",
  "BottomCta": "하단 실행 버튼",
  "BottomInfo": "하단 안내",
  "BottomNavigation": "하단 탐색",
  "Breadcrumb": "이동 경로",
  "Button": "버튼",
  "Calendar": "달력",
  "Card": "카드",
  "Carousel": "캐러셀",
  "Cascader": "단계별 선택",
  "CascaderComposition": "단계별 선택 조합",
  "Checkbox": "체크박스",
  "CheckboxGroup": "체크박스 그룹",
  "Chip": "선택 칩",
  "ChooseColor": "색상 선택",
  "ChooseTime": "시간 선택",
  "ChooseRegion": "지역 선택",
  "Clipboard": "클립보드",
  "Collapsible": "접기와 펼치기",
  "ColorPicker": "색상 선택기",
  "Combobox": "검색형 선택",
  "CommandPalette": "명령 검색",
  "Compact": "간결한 배치",
  "Container": "컨테이너",
  "ContentMotion": "내용 전환 효과",
  "ContextMenu": "상황별 메뉴",
  "CounterBadge": "숫자 배지",
  "Dark": "어두운 테마",
  "DataDisplay": "데이터 표시",
  "DataTable": "데이터 표",
  "DatePicker": "날짜 선택",
  "DateRangePicker": "기간 선택",
  "Default": "기본",
  "DescriptionList": "설명 목록",
  "DesignSystemProvider": "디자인 시스템 설정",
  "DesktopMenubar": "데스크톱 메뉴 막대",
  "DesktopShell": "데스크톱 화면 골격",
  "Dialog": "대화상자",
  "Disabled": "비활성",
  "DisplayScale": "표시 크기",
  "Divider": "구분선",
  "DurationPicker": "소요 시간 선택",
  "EmojiReactions": "이모지 반응",
  "EmptyState": "빈 상태",
  "Error": "오류",
  "EvidenceMatrix": "구현·검증 현황",
  "Explorer": "전체 탐색",
  "Feedback": "상태와 알림",
  "Field": "입력 필드",
  "FilePicker": "파일 선택",
  "Filters": "필터",
  "FloatingActionButton": "플로팅 실행 버튼",
  "Fluid": "유연한 배치",
  "Folders": "폴더",
  "Form": "입력 양식",
  "Formats": "표현 형식",
  "Formatters": "서식 변환",
  "Foundation": "글자와 아이콘",
  "Foundations": "디자인 기초",
  "Grid": "격자",
  "GroupedAvatars": "아바타 그룹",
  "Guide": "사용 안내",
  "HalfPoint": "반점 단위",
  "Heading": "제목",
  "Icon": "아이콘",
  "IconButton": "아이콘 버튼",
  "Image": "이미지",
  "ImperativeOverlays": "코드로 여는 팝업",
  "InlineConfirmation": "버튼 안에서 확인",
  "Inputs": "입력",
  "LargeText": "큰 글자",
  "Layout": "화면 기본 구조",
  "Link": "링크",
  "LiquidHintFallback": "리퀴드 효과 대체 표시",
  "List": "목록",
  "ListAndDetail": "목록과 상세",
  "ListRow": "목록 행",
  "LoadMore": "더 보기",
  "Loading": "로딩",
  "LoadingRows": "목록 로딩",
  "LongCopyWithAction": "긴 문구와 실행 버튼",
  "Manual": "수동 재생",
  "MarkDocument": "문서 표시",
  "Masonry": "높이가 다른 카드 배치",
  "Matrix": "환경별 비교",
  "Mentions": "사용자 언급",
  "MentionsInWriting": "작성 중 사용자 언급",
  "Menu": "메뉴",
  "Menubar": "메뉴 막대",
  "MixedMedia": "혼합 미디어",
  "ModalEditing": "대화상자 편집",
  "MovingRecords": "기록 이동",
  "Navigation": "탐색",
  "NonModalHelper": "화면을 가리지 않는 도움말",
  "Notes": "메모",
  "Notice": "안내 메시지",
  "NotificationFeedback": "알림 상태",
  "NumberField": "숫자 입력",
  "Onboarding": "온보딩",
  "OptionalAutoplay": "자동 재생 연동",
  "OtpField": "인증번호 입력",
  "Overlays": "오버레이",
  "Overview": "개요",
  "PackedCards": "카드 묶음",
  "Pagination": "페이지 이동",
  "PasswordField": "비밀번호 입력",
  "Paused": "일시 정지",
  "PickARange": "기간 고르기",
  "Playground": "직접 조작",
  "PointerMenu": "포인터 메뉴",
  "Popover": "팝오버",
  "Progress": "진행 표시",
  "ProgressRing": "원형 진행 표시",
  "Providers": "제공자 설정",
  "QRCode": "큐알 코드",
  "QrCode": "큐알 코드",
  "QuickActions": "빠른 실행",
  "Radio": "라디오 버튼",
  "RadioGroup": "라디오 버튼 그룹",
  "ReadOnlyAverage": "평균 점수 표시",
  "RecordTable": "기록 표",
  "Records": "기록",
  "ReducedMotion": "동작 줄이기",
  "RequiredEvidence": "필수 검증 항목",
  "Result": "결과 안내",
  "ReversibleConfirmation": "취소 가능한 확인",
  "Roles": "역할별 보기",
  "ScreenTitle": "화면 제목",
  "SearchField": "검색 입력",
  "Section": "섹션",
  "SegmentedControl": "버튼형 선택",
  "Select": "목록에서 선택",
  "SemanticLucide": "의미별 루시드 아이콘",
  "SemanticPalette": "역할별 색상",
  "ShareCode": "공유 코드",
  "SharedReducedMotion": "공통 동작 줄이기",
  "SharedScreenTransition": "공통 화면 전환",
  "Sheet": "시트",
  "SidePanel": "측면 패널",
  "Sidebar": "사이드바",
  "SignInLoading": "로그인 중",
  "SignInScreen": "로그인 화면",
  "SignUpConsent": "가입 동의",
  "SingleDisclosure": "단일 펼침",
  "Skeleton": "스켈레톤",
  "SkipNav": "본문 바로가기",
  "Slider": "슬라이더",
  "SocialLogin": "소셜 로그인",
  "Spinner": "로딩 표시",
  "Splitter": "분할 영역 조절",
  "Stack": "가로·세로 배치",
  "StandingConditions": "고정 조건",
  "Statistic": "수치 표시",
  "Steps": "단계 탐색",
  "StickyAction": "고정 실행 영역",
  "Surface": "배경 영역",
  "Switch": "스위치",
  "Tabs": "탭",
  "Tag": "태그",
  "Tags": "태그 모음",
  "TagsInput": "태그 입력",
  "Text": "본문 글자",
  "TextArea": "여러 줄 입력",
  "TextFormat": "글자 서식",
  "ThinkingOrb": "생각 중 표시",
  "Timeline": "타임라인",
  "Toast": "토스트",
  "LiquidToast": "리퀴드 토스트",
  "ToggleGroup": "토글 그룹",
  "Toggles": "토글",
  "ToneGallery": "상태별 비교",
  "Tooltip": "툴팁",
  "Top": "화면 제목과 설명",
  "TopBar": "상단 탐색 막대",
  "Tour": "사용 안내 둘러보기",
  "TransferList": "목록 간 항목 이동",
  "Tree": "트리 목록",
  "TreeSelectComposition": "트리 선택 조합",
  "UploadItem": "업로드 항목",
  "Utilities": "보조 기능",
  "Vertical": "세로 배치",
  "VerticalAxis": "세로 축",
  "VirtualList": "가상 목록",
  "VisuallyHidden": "화면 읽기 도구용 글자",
  "Watermark": "워터마크",
  "WholePoint": "정수 단위",
  "WindowedList": "가상 목록 예제",
  "Wrapped": "줄바꿈",
  "GridReveal": "격자 등장 효과",
  "EffectSurface": "배경 시각 효과",
  "ContentTransition": "내용 전환",
  "GravityLetters": "중력 글자",
  "DurationField": "소요 시간 입력",
  "TaskList": "할 일 목록",
  "Rating": "별점",
  "StepPlayer": "단계별 진행 표시",
  "NotificationBell": "알림 벨",
  "ScrollProgress": "읽기 진행 표시",
  "AnimatedStatistic": "움직이는 수치",
  "VoiceNote": "음성 메모",
  "FolderPreview": "폴더 미리보기",
  "BlobatarAvatar": "블로바타 캐릭터",
  "ActivityHeatmap": "활동 히트맵",
  "CodeBlock": "코드 블록",
  "AnimatedBlobatar": "움직이는 블로바타 캐릭터",
  "SidebarMotion": "사이드바 전환",
  "GooeyNavigation": "물방울 탐색 메뉴",
  "ReactionPicker": "반응 선택",
  "InlineConfirm": "버튼 안에서 확인",
  "LucideIcon": "루시드 아이콘"
};
