import type { Meta, StoryObj } from "@storybook/react-native";
import { SearchScreenPreview } from "./basic-screen-previews";
const meta = { title: "실험/화면/공통 화면/검색", component: SearchScreenPreview } satisfies Meta<typeof SearchScreenPreview>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = { name: "기본" };
export const Dark: Story = { name: "어두운 테마", globals: {theme:"dark"} };
export const LargeText: Story = { name: "큰 글자", globals: {textScale:"2"} };
export const Loading: Story = { name: "불러오는 중", args: {stateKind:"loading"} };
export const Empty: Story = { name: "빈 화면", args: {stateKind:"empty"} };
export const Error: Story = { name: "오류와 복구", args: {stateKind:"error"} };
export const Restricted: Story = { name: "로그인 필요", args: {stateKind:"restricted"} };
