import type { Meta, StoryObj } from "@storybook/react-native";
import { IntroductionPreview } from "./introduction-preview";
const meta = { title: "배포/화면/소개/서비스 소개", component: IntroductionPreview, args: { variant: "landing" } } satisfies Meta<typeof IntroductionPreview>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = { name: "기본" };
export const Product: Story = { name: "제품 체험 중심", args: { variant: "product" } };
export const Editorial: Story = { name: "설명과 사례 중심", args: { variant: "editorial" } };
export const Dark: Story = { name: "어두운 테마", globals: { theme: "dark" } };
export const LargeText: Story = { name: "큰 글자", globals: { textScale: "2" } };
export const ProductDark: Story = { ...Product, name: "제품 체험 중심 · 어두운 테마", globals: { theme: "dark" } };
export const ProductLargeText: Story = { ...Product, name: "제품 체험 중심 · 큰 글자", globals: { textScale: "2" } };
export const EditorialDark: Story = { ...Editorial, name: "설명과 사례 중심 · 어두운 테마", globals: { theme: "dark" } };
export const EditorialLargeText: Story = { ...Editorial, name: "설명과 사례 중심 · 큰 글자", globals: { textScale: "2" } };
