#!/usr/bin/env python3
"""Generate an original periodic value-noise alpha tile; no external image source.

react-native-svg 15.15.5 FeTurbulence renders null. Baking a shared static tile
keeps both renderers usable without a new GPU peer or per-frame pixel generation.
This is six-octave value noise, not SVG's Perlin implementation or pixel parity.
"""
import base64
import random
import struct
import zlib
from pathlib import Path

SIZE = 64
rng = random.Random(7341)
values = [0.0] * (SIZE * SIZE)
weight = 0.0
for cells in [2, 4, 8, 16, 32, 64]:
    grid = [[rng.random() for _ in range(cells)] for _ in range(cells)]
    amplitude = cells ** 0.35
    weight += amplitude
    for y in range(SIZE):
        gy = y * cells / SIZE
        iy, fy = int(gy), gy % 1
        sy = fy * fy * (3 - 2 * fy)
        for x in range(SIZE):
            gx = x * cells / SIZE
            ix, fx = int(gx), gx % 1
            sx = fx * fx * (3 - 2 * fx)
            top = grid[iy][ix] * (1 - sx) + grid[iy][(ix + 1) % cells] * sx
            bottom = grid[(iy + 1) % cells][ix] * (1 - sx) + grid[(iy + 1) % cells][(ix + 1) % cells] * sx
            values[y * SIZE + x] += (top * (1 - sy) + bottom * sy) * amplitude
raw = bytearray()
for y in range(SIZE):
    raw.append(0)
    for x in range(SIZE):
        # White luminance with variable alpha is a theme-neutral SVG mask.
        alpha = round(max(0, min(1, (values[y * SIZE + x] / weight - 0.25) * 1.5)) * 255)
        raw.extend((255, alpha))
def chunk(kind, data):
    return struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data))
png = b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', SIZE, SIZE, 8, 4, 0, 0, 0)) + chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b'')
uri = 'data:image/png;base64,' + base64.b64encode(png).decode()
target = Path(__file__).resolve().parents[1] / 'packages/design-contracts/src/internal/effect-noise.ts'
target.parent.mkdir(exist_ok=True)
target.write_text('// Generated by scripts/generate-effect-noise.py. Native FeTurbulence is unimplemented;\n// a shared static mask avoids a new runtime and keeps noise separate from dotted grain.\nexport const effectNoiseTile = "' + uri + '";\n')
print(f'Generated {SIZE}x{SIZE} tile: {len(png)} PNG bytes')
