import type { Meta, StoryObj } from "@storybook/react-native";
import { NativeComponentPreview } from "../component-examples";
const meta = { title: "배포/컴포넌트/동작/아이콘 버튼", component: NativeComponentPreview, args: { componentId: "icon-button", variant: "default" }, argTypes: { variant: { control: "select", options: ["default", "disabled", "loading"] } }, parameters: { hjm: { componentIds: ["icon-button"] }, controls: { exclude: ["componentId"] } } } satisfies Meta<typeof NativeComponentPreview>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = { name: "기본",};
export const Dark: Story = { name: "어두운 테마", globals: { theme: "dark" } };
export const LargeText: Story = { name: "큰 글자", globals: { textScale: "2" } };
export const Disabled: Story = { name: "비활성", args: { variant: "disabled" } };
export const Loading: Story = { name: "로딩", args: { variant: "loading" } };
