import { act, create, type ReactTestRenderer } from "react-test-renderer";
import { expect, it, vi } from "vitest";
import { HjmNativeProvider } from "../src/provider.js";
import { MessageComposer } from "../src/screens.js";
import { TextArea } from "../src/inputs.js";
import { IconButton } from "../src/actions.js";
import { Text } from "../src/primitives.js";
(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
it("preserves host blur, validation, native newline, and local photo-only receipt ownership", () => {
  const send = vi.fn(), blur = vi.fn(), remove = vi.fn();
  const props = {label:"사진이나 메시지를 보내세요",placeholder:"메시지",sendLabel:"보내기",value:"",onValueChange:vi.fn(),onSend:send,onBlur:blur,description:"준비 중",invalid:true,sendIcon:<Text>↑</Text>,attachments:[{id:"local",removeLabel:"사진 삭제",disabled:true,preview:<Text>사진</Text>}],onRemoveAttachment:remove};
  let tree!: ReactTestRenderer;
  act(() => {tree = create(<HjmNativeProvider><MessageComposer {...props}/></HjmNativeProvider>);});
  const input = tree.root.findByType(TextArea);
  expect(input.props.accessibilityLabel).toBe(props.label);
  expect(input.props.placeholder).toBe("메시지");
  expect(input.props.description).toBe("준비 중");
  expect(input.props.invalid).toBe(true);
  expect(input.props.submitBehavior).toBe("newline");
  act(() => {input.props.onBlur(); input.props.onSubmitEditing();});
  expect(blur).toHaveBeenCalledOnce(); expect(send).not.toHaveBeenCalled();
  const removal = tree.root.findAllByType(IconButton).find(node => node.props.label === "사진 삭제")!;
  expect(removal.props.disabled).toBe(true);
  act(() => removal.props.onPress()); expect(remove).not.toHaveBeenCalled();
  act(() => tree.root.findAllByType(IconButton).find(node => node.props.label === "보내기")!.props.onPress());
  expect(send).toHaveBeenCalledWith(""); expect(tree.root.findByType(TextArea).props.value).toBe("");
  act(() => tree.update(<HjmNativeProvider><MessageComposer {...props} pending submitMode="send"/></HjmNativeProvider>));
  act(() => tree.root.findByType(TextArea).props.onSubmitEditing()); expect(send).toHaveBeenCalledOnce();
  act(() => tree.unmount());
});
